# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cooperativa Integral - Argentina
email: no@tenemos.com
description:  Proyecto inspirado en la Cooperativa Integral Catalana (CIC).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coopintar.github.com" # the base hostname & protocol for your site
twitter_username: CoopIntAr
github_username: CoopIntAr

# Build settings
markdown: kramdown
